src/Entity/Car.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\CarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource()]
#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $model_year = null;

    #[ORM\Column(length: 255)]
    private ?string $car_condition = null;

    #[ORM\Column(nullable: true)]
    private ?int $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $location = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $carFilename = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    private ?CarMake $carmake = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getModelYear(): ?int
    {
        return $this->model_year;
    }

    public function setModelYear(int $model_year): self
    {
        $this->model_year = $model_year;

        return $this;
    }

    public function getCarCondition(): ?string
    {
        return $this->car_condition;
    }

    public function setCarCondition(string $car_condition): self
    {
        $this->car_condition = $car_condition;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarFilename(): ?string
    {
        return $this->carFilename;
    }

    public function setCarFilename(string $carFilename): self
    {
        $this->carFilename = $carFilename;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCarmake(): ?CarMake
    {
        return $this->carmake;
    }

    public function setCarmake(?CarMake $carmake): self
    {
        $this->carmake = $carmake;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\CarMake;
use App\Repository\CarMakeRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $allCars = $doctrine->getRepository(Car::class)->findAll();

        return $this->render('home/index.html.twig', [
            'cars'=> $allCars,
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/home/car-make-listing.html.twig
<div class="row bg-white">
    <div class="d-flex justify-content-between p-4 my-1">
        <div class="p-2"><h4 class="p-2">TOP BRANDS </h4></div>
        <div class="p-2"><a href="{{ path('app_car_list_all') }}" class="btn btn-outline-secondary shadow-sm">View alL <i class="bi bi-arrow-right"></i></a> </div>
    </div>
</div>
<div class="row bg-white p-4 my-2">
<div class="owl-carousel owl-theme owl-lazy owl-loaded owl-drag">
    <div class="owl-stage-outer">
        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2376px;">
            {% for i in 1..20 %}
            <div class="owl-item active" style="width: 178px; margin-right: 20px;">
                <div class="item">
                    <div class="col mb-4">
                        <div class="d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <img style="width: 50px;height: 50px" class="rounded-circle" src="/images/allan.jpeg" alt="...">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h6>carselb investments ltd</h6>
                                <div class="d-flex align-items-center flex-wrap">
                                    <!-- Rating -->
                                    <div class="d-flex gap-1">
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                    </div>
                                    <!-- End Rating -->
                                    <div class="ms-1">
                                        <span class="fw-semibold text-dark me-1">4.91</span>
                                        <span>(1.5k+ reviews)</span>
                                    </div>
                                </div>
                                <p style="font-size: 12px">This is some content from a media component.
                                    You can replace this with any content.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>

templates/home/footer.html.twig
<div class="container">
    <footer class="py-5">
        <div class="row">
            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3">
                <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
            <p>© 2022 Company, Inc. All rights reserved.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
                <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
            </ul>
        </div>
    </footer>
</div>

templates/home/header.html.twig
{% include 'home/topbar.html.twig' %}
<div class="container mb-4">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ path('app_home') }}" class="nav-link px-2 text-secondary">Home</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Catalog
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ path('app_car_list_results') }}">List View</a></li>
                        <li><a class="dropdown-item" href="#">Grid View</a></li>
                        {% if is_granted('ROLE_USER') %}
                        <li><a class="dropdown-item" href="{{ path('app_car_make_form') }}">Add Car Make</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-secondary" href="{{ path('app_pricing') }}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Pricing
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ path('app_pricing') }}">Sell</a></li>
                        <li><a class="dropdown-item" href="#">Ad promotion</a></li>
                    </ul>
                </li>
                <li><a href="#" class="nav-link px-2 text-secondary">About</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary"><i class="bi bi-question-circle"></i> Help Center</a></li>
            </ul>
            <div class="text-end">
                <a href="#" class="btn border-secondary rounded-circle me-2 position-relative">
                    <i class="bi bi-heart text-secondary"></i>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"> 9+
    <span class="visually-hidden">unread messages</span>
  </span>
                </a>
                {% if app.user %}
                    <button class="btn border-0 text-white nav-item dropdown" style="">
                        <a class=" nav-link dropdown-toggle text-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person"></i> Account
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Personal Info</a></li>
                            <li><a class="dropdown-item" href="#">Security</a></li>
                            <li><a class="dropdown-item" href="#">My Cars</a></li>
                            <li><a class="dropdown-item" href="#">Wish List</a></li>
                            <li><a class="dropdown-item" href="#">Reviews</a></li>
                            <li><a class="dropdown-item" href="#">Notifications</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}"><i class="bi bi-box-arrow-in-left"></i> Log Out</a></li>

                        </ul>
                    </button>
                {% else %}
                    <a href="{{ path('app_login') }}" type="button" class="btn border-primary text-primary shadow me-2"><i class="bi bi-person"></i> Sign in</a>
                {% endif %}
                <a href="{{ path('app_car_add') }}"  class="btn btn-primary shadow text-white"> <i class="bi bi-plus-circle"></i> Sell Car</a>
            </div>
        </div>
    </div>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}carselb.com!{% endblock %}

{% block body %}
<div class="container-fluid parallax">
    <div class="row bg-dark">
        <div class="col-md-7">
            <div class="p-4 my-4 rounded shadow shadow-sm">
                <div class="col-md-8 px-0 text-white">
                    <h1 class="display-1 text-warning fw-bold">CARSELB.com</h1>
                    <hr class="my-2">
                    <h1 class="display-4 fw-bold">Easy way to find the right car</h1>
                    <hr class="my-2">
                    <p class="lead my-3">
                        Carselb is a leading digital marketplace for the automotive industry that connects car shoppers with sellers.
                    </p>
                    <hr class="my-2">
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="p-4">
                <div class=" alert alert-light shadow my-4 p-4 mx-auto">
                    <h3 class="fw-bold">
                        Find Car
                    </h3>
                    {% if app.user %}
                        <h2>
                            Welcome, {{ app.user.username }}
                        </h2>
                    {% endif %}
                    <p class="col-md-8 lead">
                        Browse over 200,000+ cars from around the country.
                    </p>
                    <div class="lead">
                        <form action="{{ path('app_car_list_results') }}" class="form-control alert alert-light my-4">
                            <div class="form-floating">
                                <input type="search" name="q" class="form-control" id="floatingInputGrid" required>
                                <label for="floatingInputGrid">E.g Chevrolet Tahoe</label>
                            </div>
                            <button type="submit" class="my-2 btn btn-lg shadow btn-warning"><i class="bi bi-search"></i> Search By </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- top deal car listing -->
    {%  include 'home/top-deal-car-listing.html.twig' %}
    <!-- top sellers listing -->
    {% include 'home/top-sellers-listing.html.twig' %}
    <!-- latest car listing -->
    {%  include 'home/latest-car-listing.html.twig' %}
    <!-- car make listing -->
    {% include 'home/car-make-listing.html.twig' %}
</div>
{% endblock %}

templates/home/latest-car-listing.html.twig
<div class="row bg-white">
    <div class="d-flex justify-content-between p-4 my-1">
        <div class="p-2"><h4 class="p-2">LATEST</h4></div>
        <div class="p-2"><a href="{{ path('app_car_list_results') }}" class="btn btn-outline-secondary shadow">View All <i class="bi bi-arrow-right-circle"></i></a> </div>
    </div>
</div>
<div class="row bg-white p-4 my-2">
<div class="owl-carousel owl-theme owl-lazy owl-loaded owl-drag">
    <div class="owl-stage-outer">
        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2376px;">
            {% for cars in cars %}
            <div class="owl-item active" style="width: 178px; margin-right: 20px;">
                <div class="item">
                    <div class="col mb-4">
                        <!-- Card -->
                        <div class="card card-bordered shadow-none h-100">
                            <div class="card-pinned">
                                <img style="height: 170px" class="card-img-top" src="{{ asset('/uploads/' ~cars.carFilename) }}" alt="Image Description">
                            </div>
                            <div class="card-body">
                                <h6 style="font-size: 10px" class="card-title  position-relative">
                                    <a href="/car/list/chevrolet%20tahoe" class="text-dark"> {{ cars.title | upper }} </a>

                                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-dark">
                                         New
                                     </span>

                                </h6>
                                <h5 style="font-size: 13px" class="card-subtitle my-1">
                                    {{ cars.price | format_currency('UGX') }}
                                </h5>
                                <div class="card-text" style="font-size: 12px;">
                                    <div class="d-flex flex-column">
                                    <div class="d-flex justify-content-between flex-wrap">
                                        <div>
                                            <p class="me-3"> <i class="bi bi-car-front"></i>
                                                {{ cars.carmake.name | default('') }}
                                                {{ cars.modelYear }}
                                            </p>
                                        </div>

                                        <div>
                                            <p class="me-1">
                                                <i class="bi bi-geo-alt"></i> {{ cars.location }}
                                            </p>
                                        </div>
                                    </div>
                                        <div class="d-flex justify-content-between flex-wrap">
                                        <div>
                                            <span style="background:#D2f4EA;" class="pe-1 badge rounded-pill text-secondary"><small>Negotiable </small> </span>
                                        </div>
                                            <div>
                                               <span><small>Uploaded {{ cars.createdAt | ago }} </small> </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <button class="btn">
                                            <i class="bi bi-share"></i>
                                        </button>
                                    </div>
                                    <div>
                                        <button class="btn">
                                            <i class="bi bi-heart"></i>
                                        </button>
                                    </div>
                                </div>


                            </div>

                        </div>
                        <!-- End Card -->
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>

templates/home/top-deal-car-listing.html.twig
<div class="row bg-white">
    <div class="d-flex justify-content-between p-4 my-1">
        <div class="p-2"><h4 class="p-2">TOP DEALS</h4></div>
        <div class="p-2"><a href="{{ path('app_car_list_results') }}" class="btn btn-outline-secondary shadow">View All <i class="bi bi-arrow-right-circle"></i></a> </div>
    </div>
</div>
<div class="row bg-white p-4 my-2">
<div class="owl-carousel owl-theme owl-lazy owl-loaded owl-drag">
    <div class="owl-stage-outer">
        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2376px;">
            {% for cars in cars %}
            <div class="owl-item active" style="width: 178px; margin-right: 20px;">
                <div class="item">
                    <div class="col mb-4">
                        <!-- Card -->
                        <div class="card card-bordered shadow-none h-100">
                            <div class="card-pinned">
                                <img style="height: 150px; min-width: 150px" class="card-img-top" src="{{ asset('/uploads/' ~cars.carFilename) }}" alt="Image Description">
                            </div>
                            <div class="card-body">
                                <h6 style="font-size: 10px" class="card-title  position-relative">
                                    <a href="{{ path('app_car_show',{title: cars.title}) }}" class="text-dark"> {{ cars.title | upper }} </a>

                                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning text-dark">
                                         New
                                     </span>

                                </h6>
                                <h5 style="font-size: 13px" class="card-subtitle my-1">
                                    {{ cars.price | format_currency('UGX') }}
                                </h5>
                                <div class="card-text" style="font-size: 12px;">
                                    <div class="d-flex flex-column">
                                    <div class="d-flex justify-content-between flex-wrap">
                                        <div>
                                            <p class="me-3">
                                                <i class="bi bi-car-front"></i>
                                                {{ cars.carmake.name | default('') }}
                                                {{ cars.modelYear }}
                                            </p>
                                        </div>

                                        <div>
                                            <p class="me-1">
                                                <i class="bi bi-geo-alt"></i> {{ cars.location }}
                                            </p>
                                        </div>
                                    </div>
                                        <div class="d-flex justify-content-between flex-wrap">
                                        <div>
                                            <span style="background:#D2f4EA;" class="pe-1 badge rounded-pill text-secondary"><small>Negotiable </small> </span>
                                        </div>
                                            <div>
                                               <span><small>Uploaded {{ cars.createdAt | ago }} </small> </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <div>
                                        <button class="btn">
                                            <i class="bi bi-share"></i>
                                        </button>
                                    </div>
                                    <div>
                                        <button class="btn">
                                            <i class="bi bi-heart"></i>
                                        </button>
                                    </div>
                                </div>


                            </div>

                        </div>
                        <!-- End Card -->
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>

templates/home/top-sellers-listing.html.twig
<div class="row bg-white">
    <div class="d-flex justify-content-between p-4 my-1">
        <div class="p-2"><h4 class="p-2">TOP SELLERS </h4></div>
        <div class="p-2"><a href="{{ path('app_car_list_all') }}" class="btn btn-outline-secondary shadow">View all <i class="bi bi-arrow-right-circle"></i></a> </div>
    </div>
</div>
<div class="row bg-white p-4 my-2">
<div class="owl-carousel owl-theme owl-lazy owl-loaded owl-drag">
    <div class="owl-stage-outer">
        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 2376px;">
            {% for i in 1..20 %}
            <div class="owl-item active" style="width: 178px; margin-right: 20px;">
                <div class="item">
                    <div class="col mb-4">
                        <div class="d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <img style="width: 50px;height: 50px" class="rounded-circle" src="/images/allan.jpeg" alt="...">
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h6>carselb investments ltd</h6>
                                <div class="d-flex align-items-center flex-wrap">
                                    <!-- Rating -->
                                    <div class="d-flex gap-1">
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                        <i class="bi bi-star-fill text-warning"></i>
                                    </div>
                                    <!-- End Rating -->
                                    <div class="ms-1">
                                        <span class="fw-semibold text-dark me-1">4.91</span>
                                        <span>(1.5k+ reviews)</span>
                                    </div>
                                </div>
                                <p style="font-size: 12px">This is some content from a media component.
                                    You can replace this with any content.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>

templates/home/topbar.html.twig
<header>
    <div class="container text-info ">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-2 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-2 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{{ asset('logo/ifentuisystems.png') }}" class="rounded" width="50" height="50" />
                </a>
                <h3 class="mb-2 mb-md-0 text-muted">CARSELB.COM</h3>
            </div>
            <ul class="align-items-center nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#"><i class="bi bi-facebook"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="bi bi-twitter"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="bi bi-instagram"></i></a></li>
                <li class="ms-3"><a class="text-muted" href="#"><i class="bi bi-youtube"></i></a></li>
            </ul>
        </div>
    </div>
</header>